version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"  # FastAPI
      - "8050:8050"  # Dash
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - .:/app
    restart: unless-stopped